---
- name: This is a simple payb to understand command line arguments
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: working with httpd
      yum:
        name: "{{pkg}}"
        state: "{{req_state}}"
