#!/user/bin/ansible-playbook
- name: Usage of debug module
  hosts: localhost
  tasks:
    - name: printing a variable value using debug module
      debug:
        # msg: "The host name is: {{inventory_hostname}}"
        var: invertory_hostname
